### ISSUE TITLE
Unhandled exception occured whiule running /07.Labs/CsharpOllamaCodeSpaces/src/Sample03

### ISSUE THREAD

**Issue by maroldo26** [microsoft/Phi-3CookBook#116]
[x] bug report

### Minimal steps to reproduce
This issue can be reproduced by running the sample in local development environment or via Github codespaces.
Exception occurs at Program.cs Line No: 107

### Error log
> Phi-3 response (using semantic memory).
Unhandled exception. Microsoft.SemanticKernel.HttpOperationException: json: cannot unmarshal array into Go struct field .tools.function.parameters.properties.type of type string
Status: 400 (Bad Request)
>
>Content:
{"error":{"message":"json: cannot unmarshal array into Go struct field .tools.function.parameters.properties.type of type string","type":"invalid_request_error","param":null,"code":null}}
>
>Headers:
Date: Fri, 26 Jul 2024 10:11:40 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 187
>
>---> Azure.RequestFailedException: json: cannot unmarshal array into Go struct field .tools.function.parameters.properties.type of type string
>Status: 400 (Bad Request)
>
>Content:
{"error":{"message":"json: cannot unmarshal array into Go struct field .tools.function.parameters.properties.type of type string","type":"invalid_request_error","param":null,"code":null}}

**Comment by leestott** [comment]
@elbruno could you take a look at this?

**Comment by elbruno** [comment]
Hi @maroldo26 

I could not reproduce the error. I'll advice to update the nuget packages and test again, I'll update the packages in the repo and test it again.

Best

**Comment by elbruno** [comment]
Update: the RAG demo works locally, and also running in a local DevContainer. The main issue seems to be related to the RAG scenario in CodeSpaces, still not working.

We'll looking for the fix, and I'll update the issue as soon as it's fixed.

Best.

**Comment by pugafran** [comment]
Any news?
