### ISSUE TITLE
Broken Reference to image in `code/07.Lab/translations/zh-tw/01/Apple/phi3ext/README.md`

### ISSUE THREAD

**Issue by john0isaac** [microsoft/Phi-3CookBook#125]
```bash
Checked 767 links in 238 files.
Found 1 issues in the following files:
	File 'Phi-3CookBook/code/07.Lab/translations/zh-tw/01/Apple/phi3ext/README.md', line 11
images/feature-x.png is broken.
```

https://github.com/microsoft/Phi-3CookBook/blob/main/code/07.Lab/translations/zh-tw/01/Apple/phi3ext/README.md?plain=1#L11

**Comment by leestott** [comment]
@doggy8088 can you please take a look at this on your translation file

**Comment by doggy8088** [comment]
@leestott I already sent a PR: https://github.com/microsoft/Phi-3CookBook/pull/126
