### ISSUE TITLE
Please provide examples for function calling (aka "tools")

### ISSUE THREAD

**Issue by stippi2** [microsoft/Phi-3CookBook#13]
Thanks for making this cook book available and Phi-3 available!

In short:

1. I would love an example of a system message that declares some tools with JSON Object Schema function definitions, and explains how to invoke them.
2. How are function results even returned to the model? There seem to be no dedicated roles for that. (Why would the model realize that it needs to compile the results of a function call into a coherent message to the actual user?)

For a bit more context:

I would like to use Phi-3 in an application with function calling. In my Phi-3 evaluation, I struggle to come up with a system message that successfully explains function calling to the model. I have Phi-3 running on LM Studio on a PC and Ollama on a Mac. When I craft a system message that declares tools and instructs the model how to invoke them, the best I could achieve was that the model replied along the lines of "If I wouldn't run in a simulation, I would call the tool X with the parameters Y to answer this request." Instead of just doing it. In many cases, I get large blobs of text after the initial reply that look like training data. The "training data" looks very similar to what I am trying to do with my system message. Sometimes it contains sections that I didn't think of and are not just a rephrase of my attempt at a system prompt.

I've also worked with LangChain and the experimental Ollama function calling package. The system message it generates is very simple. As long as there is a single tool defined, invoking it works reliable. But when multiple tools are defined, and the model needs to decide whether it even needs a tool at all, the generated output becomes very unreliable, often with rambling appended that looks like training data. Or it generates a function call, but continous with halucinated results for the call, instead of waiting for them in the next message.

**Comment by leestott** [comment]
Hi @stippi2 

Can I play the following back to ensure I understand what your asking?

Example: System message to demonstrate how you can declare tools using OpenAPI and instruct your Phi-3 model on how to invoke these functions effectively. 

We will define two simple tools: `greet` which returns a greeting. Our goal is to provide clear instructions for the model so it understands when and how to use these functions in responses.

Here's an example of what your OpenAPI definition might look like:

```yaml
openapi: "3.0.0"
info:
  title: Tool Interactions API
  version: "1.0.0"
servers:
- url: http://myapp.com/docs/swagger#!/tools
paths:
  /greet/{name}:
    get:
      summary: Greet a person by name
      description: This tool generates a greeting message for the provided name parameter.
      responses:
        200:
          description: Successful response containing a greeting message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
exampleParameters:
  name: "Hello"
      $ref: '#/paths/{name}/get'
```

Now, let's craft a system message to guide the Phi-3 model on how it should handle this API request and invoke the `greet` tool.

System Message:
```
[START]
{
  "api": {
    "type": "tool",
    "name": "greet",
    "parameters": [
      {
        "key": "name",
        "value": "Hello"
      }
    ],
    "responseFormat": "application/json",
    "functionCall": true,
    "functionName": "invoke_tool",
    "dataType": "object",
    "expectedResponseSchema": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      },
      "required": ["message"]
    }
  }
}
[END]
```

In this system message, we're informing the Phi-3 model that it should invoke a tool called `greet` with the parameter "Hello". We also specify the expected response format and schema using OpenAPI definitions. The `[START]` and `[END]` tokens mark the beginning and end of the instruction block for clarity.

Phi-3, LM Studio and Ollama should be able to understand this message based on their understanding of your APIs' OpenAPI specifications. When you invoke Phi-3 using the provided system message:

```
invoke_tool with name = Hello
```

Phi-3 will correctly call the `greet` tool, and it is expected that it would return a response like this in JSON format (assuming there's an implementation for greeting):

```json
{
  "message": "Hello, nice to meet you!"
}
```

Phi-3 should then produce the corresponding human-readable message based on your Phi model training:

```
Hi! I got a request using the `greet` tool with name = Hello. The response from the tool is: "Hello, nice to meet you!".
```

Remember that you might need additional setup for your applications (e.g., API server configuration) or adjustments in Phi-3's training and model logic if you run into issues when invoking functions.

**Comment by leestott** [comment]
@stippi2 Ok so this is purely down to system message or metaprompt 

Creating a final prompt for Phi-3 with embedded tools involves structuring commands and responses in a way that clearly indicates when a tool function is being invoked. 

The system should parse these invocations, execute the corresponding action (tool usage), and then seamlessly integrate the results back into user interactions. 

Here's an example of how this can be achieved with a custom metaprompt/system message: see https://learn.microsoft.com/azure/ai-services/openai/concepts/system-message

### System message for Tools Embedded

```plaintext
You are a virtual assistant capable of handling various tasks through a series of tools designed to interact with different APIs and systems. Based on the user's input, identify which tool function should be used and execute it accordingly. Below is an overview of available tools:

1. `get_weather_forecast`: Retrieves weather forecast for 5 days in a given location (latitude, longitude).
2. `find_on_spotify`: Finds tracks, artists, albums or playlists on Spotify using queries and types.
3. ... [rest of the tools as listed] ...

To use a tool function:
- Specify the name of the tool followed by its parameters within backticks (`). For example, `get_weather_forecast({latitude: 40.7128, longitude: -74.0060})`.
- Ensure that you provide all required parameters in a valid JSON format if needed.

Upon receiving user input or task requirements, determine the appropriate tool to use and execute it. Integrate the results from tools into your responses to the users as follows:

1. If a tool function successfully executes and returns data (e.g., weather forecast), append its result directly in the response message using clear formatting (e.g., "The 5-day weather forecast for New York City is:").
2. When invoking tools with parameters, ensure you describe the task context clearly to maintain consistency and understanding. For example: "Based on your location at [latitude, longitude], here's today's weather."
3. If multiple tool functions could be relevant or no specific tool is identified for a given request, carefully choose one based on user needs, or suggest alternatives if necessary.

Here are some examples of how to format interactions:

Example 1 (Weather Forecast):
- User Input: "What's the weather like in Tokyo today?"
- Assistant Response: "Based on your location at [Tokyo coordinates], here's today's weather forecast."

Example Tool Invocation: `get_weather_forecast({latitude: 35.6895, longitude: 139.6917})`
- Assistant Response Integration: "Based on your location in Tokyo (35.6895, 139.6917), the weather forecast for today includes a high of 24°C and no precipitation."

Example 2 (Spotify Search):
- User Input: "Find me some popular tracks by Ed Sheeran"
- Assistant Response Invoking Tool: `find_on_spotify({query: 'Ed Sheeran', types: ['artist']})`
- Assistant Response Integration: "Based on your request for Ed Sheeran, here are the top 5 popular tracks by him."

Remember to maintain a friendly and engaging tone in all interactions while providing accurate information. Continue learning from user feedback to improve responses over time.
```

This prompt format provides clear instructions for tool usage and response integration, ensuring that Phi-3 can effectively utilize the tools within its capabilities without getting overwhelmed.

**Comment by stippi2** [comment]
Thanks a lot for that! Hope it's OK, I would like to clarify how the prompt towards the model evolves during the turns of the conversation with the user with tool invokations.

Assume your long system message is stored in a variable named `systemPrompt`. Somewhere in the system prompt, I would integrate a section about available real-time data, like the users current location with longitude and latitude and the current time and date, for example.

The initial prompt could be (line-breaks for clarity):

```plaintext
<|system|>${systemPrompt}<|end|>
<|user|>Hi, what time is it?<|end|>
<|assistant|>
```

Since the time can be found in the system prompt, I would expect Phi-3 to reply with something like:

```plaintext
It's half past ten.
```

The user could follow up with a question about the weather:

```plaintext
<|system|>${systemPrompt}<|end|>
<|user|>Hi, what time is it?<|end|>
<|assistant|>It's half past ten.<|end|>
<|user|>And what's the weather like?<|end|>
<|assistant|>
```

From your explanation above, I would expect the assistant replies with:

```plaintext
`get_current_weather({latitude: 35.6895, longitude: 139.6917})`
```

In my app, I detect the tool invokation, make the API call to the weather service and now I want to forward the JSON response to the model. How would the prompt now look like? Do I need to use the "user" role?

```plaintext
<|system|>${systemPrompt}<|end|>
<|user|>Hi, what time is it?<|end|>
<|assistant|>It's half past ten.<|end|>
<|user|>And what's the weather like?<|end|>
<|assistant|>`get_current_weather({latitude: 35.6895, longitude: 139.6917})`<|end|>
<|user|>???<|end|>
<|assistant|>
```

What do I insert for the `???` question marks? Do I indeed use the "user" role? If so, why does the model know it needs to rephrase that, if the user seemingly already has this information? Is the above concatenation of the message turns into the prompt even how it works at all?

Thanks!

**Comment by kinfey** [comment]
I will upgrade the content to talk about this in next few weeks ， thanks

**Comment by jivaniyash** [comment]
Hello [stippi2](https://github.com/stippi2),
Are you using ONNX runtime / onnxruntime_genai? I don't see the documentation to use the tool_calling feature. I see the LLama_cpp has compatibility of using tool_calls - https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#function-calling.

**Comment by stippi2** [comment]
> Hello [stippi2](https://github.com/stippi2), Are you using ONNX runtime / onnxruntime_genai?

I am using different runtimes, but have not yet tried ONNX. I use LM Studio and Ollama for the most part. Both runtimes don't have native support for tools.

By "native support", I mean they would read the `tools` array from the OpenAI POST request, translate that into a description the model understands, merges it with the system message you provide, detects attempts to use a tool by the model, extracts that and passes the tool invokation back in the HTTP request accordingly.

These steps I described are what I am interested in doing myself, and guidance on that is the subject of this issue.

**Comment by leestott** [comment]
Hi @stippi2 

Can I close this issue

**Comment by stippi2** [comment]
Hi, I see lots of content was added in the meantime. Can you point me at where you discuss function calling? I didn't find it with a quick glance. Would also be useful for people reading this issue later.

**Comment by leestott** [comment]
Function Calling Template 

```
<|system|>
"You are an AI assistant that can help the user with a variety of tasks. You have access to the following functions:

[
    {
        "name": "function_name",
        "description": "function_description",
        "parameters": [
            {
                "name": "parameter_name",
                "type": "parameter_type",
                "description": "parameter_description"
            },
            ...
        ],
        "required": [ "required_parameter_name_1", ... ],
        "returns": [
            {
                "name": "output_name",
                "type": "output_type",
                "description": "output_description"
            },
            ...
        ]
    },
    ...
] 

When the user asks you a question, if you need to use functions, provide function calls in the format:
[
    { "name": "function_name", "params": { dictionary containing parameters}, "output": "The output variable name, to be possibly used as input for another function"}.
    ...
]<|end|>
<|user|>
User Query<|end|>
<|assistant|>
```

Function Calling Examples 

```
<|system|>
You are an AI assistant that can help the user with a variety of tasks. You have access to the functions provided by the schema below:

<|functions_schema|>
[
    {
        "name": "get_tweets_by_hashtag",
        "description": "Retrieves tweets containing a given hashtag",
        "parameters": [
            {
                "name": "hashtag",
                "type": "string",
            },
            {
                "name": "count",
                "type": "int",
            }
        ],
        "required": [ "hashtag" ],
        "returns": [
            {
                "name": "tweets",
                "type": "list[string]",
            }
        ]
    },
    {
        "name": "get_value_from_dict",
        "description": "Retrieves the value from a dictionary for a given key",
        "parameters": [
            {
                "name": "dictionary",
                "type": "dict[string, any]",
            },
            {
                "name": "key",
                "type": "string",
            }
        ],
        "required": [ "dictionary", "key" ],
        "returns": [
            {
                "name": "value",
                "type": "any",
            }
        ]
    },
    {
        "name": "concatanate_strings",
        "description": "Concatanates a list of strings into a single string",
        "parameters": [
            {
                "name": "list_of_strings",
                "type": "list[string]",
            }
        ],
        "required": [ "list_of_strings" ],
        "returns": [
            {
                "name": "concatanated_string",
                "type": "string",
            }
        ]
    },
    {
        "name": "get_sentiment_analysis",
        "description": "Performs sentiment analysis on a given list of strings, by calling a sentiment analysis model. Returns Positiveness Scale from -10 to +10 (1 increments)",
        "parameters": [
            {
                "name": "text",
                "type": "list[string]",
            }
        ],
        "required": [ "text" ],
        "returns": [
            {
                "name": "sentiment",
                "type": "int",
            }
        ]
    },
    {    
        "name": "get_mean",
        "description": "Calculates the mean of a list of integers",
        "parameters": [
            {
                "name": "nummbers",
                "type": "list[int]",
            }
        ],
        "required": [ "numbers" ],
        "returns": [
            {
                "name": "mean",
                "type": "float",
            }
        ]
    }.
    {
        "name": "send_email",
        "description": "Sends an email with the given subject, body, and recipient",
        "parameters": [
            {
                "name": "subject",
                "type": "string",
            },
            {
                "name": "body",
                "type": "string",
            },
            {
                "name": "recipient",
                "type": "string",
            }
        ],
        "required": [ "subject", "body", "recipient" ],
        "returns": []
    },
    {
        "name": "output_to_current_chat",
        "description": "Outputs a message to the current chat or conversation",
        "parameters": [
            {
                "name": "message",
                "type": "string",
            }
        ],
        "required": [ "message" ],
        "returns": []
    },
    {
        "name": "turn_into_string",
        "description": "Returns the string representation of a value of any data type",
        "parameters": [
            {
                "name": "value",
                "type": "any",
            }
        ],
        "required": [ "value" ],
        "returns": [
            {
                "name": "value_string",
                "type": "string",
            }
        ]
    }
] 
When the user asks you a question, if you need to use functions, provide ONLY ALL OF THE function calls, ALL IN ONE PLACE, in the format:
<|function_calls|>
[
    { "name": "function_name", "kwargs": {"kwarg_1": "value_1", "kwarg_2": "value_2"}, "returns": ["output_1"]},
    { "name": "other_function_name", "kwargs": { "kwarg_3": "$output_1$"}, "returns": ["output_2", "output_3"]},
    ...
]
<|end_function_calls|>

If you need to modify strings ONLY USE THE AVAILABLE FUNCTIONS GIVEN TO YOU. IF AND ONLY IF you don't need to use functions, give your answer in between <|answer|> and <|end_answer|> blocks. For your thoughts and reasoning behind using or not using functions, place ALL OF THEM in between a SINGLE <|thoughts|> and <|end_thoughts|> block, before the <|function_calls|> and <|end_function_calls|> tags, like so:

<|thoughts|>
The user wants X, to do that, I should call the following functions:
1. function_name: Reasoning,
2. function_name_2: Reasoning2,
3. etc.
<|end_thoughts|>

Provide nothing else than the information in the <|function_calls|> & <|end_function_calls|>, <|answer|> & <|end_answer|> and <|thoughts|> & <|end_thoughts|> blocks.<|end|>
<|user|>
Can you send my friend (jasper3131@gmail.com) an email about the current sentiment about MMA in twitter?<|end|>
<|assistant|>
```

**Comment by leestott** [comment]
@stippi2 closing this with examples provided.
