### ISSUE TITLE
LabsPhi3_sk03 does not output things

### ISSUE THREAD

**Issue by Barshan-Mandal** [microsoft/Phi-3CookBook#145]
phi3  says the image is blurrish ,so it is inappropriate to describe 

phi3 says the audio is corrupted

no way to add multiple documents for rag

**Comment by leestott** [comment]
Hi @Barshan-Mandal  are you taking the semantic Kernel samples from https://github.com/elbruno/phi3-labs by @elbruno?

If so please raise issues on that repo?

**Comment by Barshan-Mandal** [comment]
> Hi @Barshan-Mandal are you taking the semantic Kernel samples from https://github.com/elbruno/phi3-labs by @elbruno?
> 
> If so please raise issues on that repo?

do u need yo raise the issue on that repo?

**Comment by leestott** [comment]
Please raise the issue on that repo yes @elbruno for your info
