### ISSUE TITLE
typo about int4

### ISSUE THREAD

**Issue by rockets-cn** [microsoft/Phi-3CookBook#17]
"Using Intel NPU acceleration, this library does not affect the traditional encoding process. You only need to use this library to quantize the original Phi-3 model, such as FP16, INT4，such as"
I have tried int4 but not working so I check the doc from intel doc"https://github.com/intel/intel-npu-acceleration-library".
it seems that the low is int8 not int4
so maybe you have to modified to int8 like
" Using Intel NPU acceleration, this library does not affect the traditional encoding process. You only need to use this library to quantize the original Phi-3 model, such as FP16, INT8，such as"

**Comment by kinfey** [comment]
Oh thanks I will update the content to fixed

**Comment by kinfey** [comment]
Hi Intel update now ,support INT 4

**Comment by alessandropalla** [comment]
Int4 is supported, have a look at https://github.com/intel/intel-npu-acceleration-library/blob/main/examples/phi-3.py

Also be sure to use the latest NPU driver: 
- Windows: https://www.intel.com/content/www/us/en/download/794734/intel-npu-driver-windows.html
- Linux: https://github.com/intel/linux-npu-driver
