### ISSUE TITLE
Using Phi3 with Langgraph, Multi agent framework 

### ISSUE THREAD

**Issue by hunaidkhan2000** [microsoft/Phi-3CookBook#184]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Using Phi 3 with Langgraph

### Any log messages given by the failure
> NA

### Expected/desired behavior
> Multi agent framework with routing 

### OS and Version?
> Windows 10

### Mention any other details that might be useful
I am trying to use Phi 3 mini 128 instruct with Langgraph for a multi-agent framework where it can route requests accurately. However, Phi 3 is not able to route the queries properly to a specific tool. Can anyone help? Does Phi 3 work with Langgraph, and does it support function calling or tool calling?
> ---------------------------------------------------------------

**Comment by hunaidkhan2000** [comment]
@leestott  I just want to understand if Phi 3 supports function calling or can be used with Langgraph. There are many  Open source LLM models which does not support function calling.

**Comment by leestott** [comment]
Hi @hunaidkhan2000 Phi-3 does support function calling. This feature allows the model to interact with external functions, APIs, or tools, making it highly versatile for various applications.

There a nice example at  https://medium.com/@mauryaanoop3/unleashing-llms-functional-calling-with-langchain-ollama-and-microsofts-phi-3-part-2-10fae91d7b01
