### ISSUE TITLE
Missing global settings in example

### ISSUE THREAD

**Issue by Penitto** [microsoft/Phi-3CookBook#29]
Hi! 

There is missing `peft_config` in [finetune example](https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/Phi-3-finetune-lora-python.ipynb): it is not defined.

Also some variables are not used (`lora_dropout , lora_r, etc`). It seems like they should be used in peft.LoraConfig.

**Comment by andmev** [comment]
This is what I used:

```python
peft_config = LoraConfig(
    r=lora_r,
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    task_type=TaskType.CAUSAL_LM,
    target_modules=target_modules,
)
```

**Comment by leestott** [comment]
@andmev  would you like to PR a new notebook sample?

**Comment by leestott** [comment]
example update please confirm if you have any issues https://github.com/microsoft/Phi-3CookBook/tree/main/code/04.Finetuning

**Comment by andmev** [comment]
@leestott also I would check the test dataset length if it is less than 500
```python
%%time
test_size = len(dataset_chatml['test'])
metricas = dataset_chatml['test'].select(range(0,test_size)).map(calculate_rogue, batched=False)
```
Rest works fine.
Thanks

**Comment by Penitto** [comment]
@leestott can you please explain why do you use 2 different tokenizers: 1st with `padding_side='right'`, 2nd with `padding_side='left'` ?
