### ISSUE TITLE
Special tokens have been added in the vocabulary

### ISSUE THREAD

**Issue by don-tpanic** [microsoft/Phi-3CookBook#38]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
```
from transformers import AutoTokenizer

checkpoint_path = "microsoft/Phi-3-mini-4k-instruct"
tokenizer = AutoTokenizer.from_pretrained(checkpoint_path)
```

### Any log messages given by the failure
> `Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.`

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux 22.04

### azd version?
> run `azd version` and copy paste here.

### Versions
> transformers 4.36.0

### Mention any other details that might be useful

From the message it seems like I'd have to free the embedding layers for fine-tuning? But looking at this example, I couldn't see if embedding layers are made trainable when using LoRA - https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/Phi-3-finetune-lora-python.ipynb
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by leestott** [comment]
Hi can you try this example https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/olive-ort-example/README.md

**Comment by leestott** [comment]
Updated samples https://github.com/microsoft/Phi-3CookBook/tree/main/code/04.Finetuning
