### ISSUE TITLE
Fine tune vision model with multiple images

### ISSUE THREAD

**Issue by pbarker** [microsoft/Phi-3CookBook#50]
Hello, is it possible to fine tune the vision model with multiple images?

**Comment by leestott** [comment]
yes see https://wandb.ai/byyoung3/mlnews3/reports/How-to-fine-tune-Phi-3-Vision-on-a-custom-dataset--Vmlldzo4MTEzMTg3

**Comment by pbarker** [comment]
Hey @leestott thanks for getting back so quick. I see how to do that with a single image, but not with multiple, are there any examples of how to do that?

**Comment by leestott** [comment]
Work in progress on samples

**Comment by leestott** [comment]
@pbarker please see https://github.com/microsoft/Phi-3CookBook/blob/main/md/04.Fine-tuning/FineTuning_Vision.md
