### ISSUE TITLE
Question: Image size and count limits 

### ISSUE THREAD

**Issue by oroojlooy** [microsoft/Phi-3CookBook#53]
Is there any limit on the image size to pass to the Phi3-vision? 
Also, what is maximum number of images that Phi3-vision can take?

**Comment by leestott** [comment]
Here are some key points about Phi-3 Vision:

Image Size Limit:
There isn’t a specific image size limit mentioned for Phi-3 Vision.
However, it’s essential to consider the available memory and computational resources of the device when passing images to the model.

Context Length:
Phi-3 Vision supports up to 128K context length in tokens.
[This allows for extensive multimodal reasoning, making it adept at understanding and generating content from complex visual inputs like charts, graphs, and tables](https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/phi-3-vision-catalyzing-multimodal-innovation/ba-p/4170251) and [Hugging Face Model] https://huggingface.co/microsoft/Phi-3-vision-128k-instruct.

Number of Images:
The model itself doesn’t have a fixed limit on the number of images it can process.
However, practical considerations (such as memory constraints) will determine how many images you can effectively pass to Phi-3 Vision.
Remember to optimize image sizes based on available resources and use cases!
