### ISSUE TITLE
Broken links: NVIDIA's AI

### ISSUE THREAD

**Issue by doggy8088** [microsoft/Phi-3CookBook#56]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

# Broken links

https://github.com/microsoft/Phi-3CookBook/blob/main/md/03.Inference/Jetson_Inference.md

![image](https://github.com/microsoft/Phi-3CookBook/assets/88981/020610ff-62e5-462d-ad5e-86cd0bb4fe0c)

**Comment by leestott** [comment]
issues resolved.
