### ISSUE TITLE
I have some ideas to improve phi-3 models further

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/Phi-3CookBook#81]
How can I contact member of the "team phi"?
I really think I can help but I can't do it alone.

**Comment by leestott** [comment]
Hi @0wwafa so you can simply do this by creating a discussion or making a PR see the Models discussions https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx/discussions?status=open&type=discussion

**Comment by 0wwafa** [comment]
thanks.
