### ISSUE TITLE
what is the reason for this 'Phi-3-V only supports batch_size == 1'?

### ISSUE THREAD

**Issue by hm-ca** [microsoft/Phi-3CookBook#85]
looking at the official fiunetuning code, I see this line 207 here:https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/vision_finetuning/finetune_hf_trainer_docvqa.py

assert len(examples) == 1, 'Phi-3-V only supports batch_size == 1'

**Comment by leestott** [comment]
@ChenRocks would you like to comment on this query.

**Comment by ChenRocks** [comment]
Hi @hm-ca we limit batch_size (per GPU) == 1 to make the implementation simpler. Larger effective batch_size is achieved by multi-gpu and gradient accumulation. What's your use case needing a larger batch_size per GPU?

**Comment by hm-ca** [comment]
Thanks @ChenRocks and @leestott for chiming in

I'm actually training on 8xH100 80GB with gradient accumulation and its going great. However those GPUs have 80GB memory each and the model is using only ~45/80GB from each GPU regardless of the number of accumulations steps. My effective batch size is currently 32.

I'm now wondering if I can speed up the training by increasing the per_device_train_batch_size from 1 to a higher value so I can reduce the overall number of iterations

Make sense?

**Comment by CS123n** [comment]
Looking forward to supporting larger batch sizes.

**Comment by ChenRocks** [comment]
The scripts were intended to be tutorial purpose than optimized for speed. Here's an example code snippet how you can change to support per GPU batch_size > 1 for hateful memes. Please make sure to properly set the training_args (`per_device_train_batch_size` and `gradient accumulation_steps`).

```python
    def __call__(self, examples):
        IGNORE_INDEX = -100
        all_input_ids = []
        all_label_ids = []
        all_pixel_values = []
        all_image_sizes = []
        for example in examples:
            image = example['images'][0]
            text_dict = example['texts'][0]

            question = text_dict['user']
            answer = text_dict['assistant']
            prompt_message = {
                'role': 'user',
                'content': f'<|image_1|>\n{question}',
            }

            prompt = self.processor.tokenizer.apply_chat_template(
                [prompt_message], tokenize=False, add_generation_prompt=True
            )
            answer = f'{answer}<|end|>\n<|endoftext|>'

            # mask questions for labels
            inputs = self.processor(prompt, [image], return_tensors='pt')
            prompt_input_ids = inputs['input_ids']
            # Do not add bos token to answer
            answer_input_ids = self.processor.tokenizer(
                answer, add_special_tokens=False, return_tensors='pt'
            )['input_ids']
            input_ids = torch.cat([prompt_input_ids, answer_input_ids], dim=1)
            labels = torch.cat(
                [
                    torch.tensor([IGNORE_INDEX] * len(prompt_input_ids[0])).unsqueeze(0),
                    answer_input_ids,
                ],
                dim=1,
            )

            # prepare expected shape for pad_sequence
            all_input_ids.append(input_ids.squeeze(0).unsqueeze(1))
            all_label_ids.append(labels.unsqueeze(1))

            all_pixel_values.append(inputs['pixel_values'])
            all_image_sizes.append(inputs['image_sizes'])

        input_ids = torch._C._nn.pad_sequence(
            all_input_ids, batch_first=True, padding_value=self.processor.tokenizer.pad_token_id
        ).squeeze(2)
        labels = torch._C._nn.pad_sequence(
            all_label_ids, batch_first=True, padding_value=IGNORE_INDEX
        ).squeeze(2)
        attention_mask = input_ids.ne(self.processor.tokenizer.pad_token_id)
        pixel_values = torch.cat(all_pixel_values, dim=0)
        image_sizes = torch.cat(all_image_sizes, dim=0)

        inputs = {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'labels': labels,
            'pixel_values': pixel_values,
            'image_sizes': image_sizes,
        }
        return inputs
```

**Comment by hm-ca** [comment]
Thanks @ChenRocks for sharing this code snippet!

I integrated in and it's working great now.

**Comment by vjagannath786** [comment]
> The scripts were intended to be tutorial purpose than optimized for speed. Here's an example code snippet how you can change to support per GPU batch_size > 1 for hateful memes. Please make sure to properly set the training_args (`per_device_train_batch_size` and `gradient accumulation_steps`).
> 
>     def __call__(self, examples):
>         IGNORE_INDEX = -100
>         all_input_ids = []
>         all_label_ids = []
>         all_pixel_values = []
>         all_image_sizes = []
>         for example in examples:
>             image = example['images'][0]
>             text_dict = example['texts'][0]
> 
>             question = text_dict['user']
>             answer = text_dict['assistant']
>             prompt_message = {
>                 'role': 'user',
>                 'content': f'<|image_1|>\n{question}',
>             }
> 
>             prompt = self.processor.tokenizer.apply_chat_template(
>                 [prompt_message], tokenize=False, add_generation_prompt=True
>             )
>             answer = f'{answer}<|end|>\n<|endoftext|>'
> 
>             # mask questions for labels
>             inputs = self.processor(prompt, [image], return_tensors='pt')
>             prompt_input_ids = inputs['input_ids']
>             # Do not add bos token to answer
>             answer_input_ids = self.processor.tokenizer(
>                 answer, add_special_tokens=False, return_tensors='pt'
>             )['input_ids']
>             input_ids = torch.cat([prompt_input_ids, answer_input_ids], dim=1)
>             labels = torch.cat(
>                 [
>                     torch.tensor([IGNORE_INDEX] * len(prompt_input_ids[0])).unsqueeze(0),
>                     answer_input_ids,
>                 ],
>                 dim=1,
>             )
> 
>             # prepare expected shape for pad_sequence
>             all_input_ids.append(input_ids.squeeze(0).unsqueeze(1))
>             all_label_ids.append(labels.unsqueeze(1))
> 
>             all_pixel_values.append(inputs['pixel_values'])
>             all_image_sizes.append(inputs['image_sizes'])
> 
>         input_ids = torch._C._nn.pad_sequence(
>             all_input_ids, batch_first=True, padding_value=self.processor.tokenizer.pad_token_id
>         ).squeeze(2)
>         labels = torch._C._nn.pad_sequence(
>             all_label_ids, batch_first=True, padding_value=IGNORE_INDEX
>         ).squeeze(2)
>         attention_mask = input_ids.ne(self.processor.tokenizer.pad_token_id)
>         pixel_values = torch.cat(all_pixel_values, dim=0)
>         image_sizes = torch.cat(all_image_sizes, dim=0)
> 
>         inputs = {
>             'input_ids': input_ids,
>             'attention_mask': attention_mask,
>             'labels': labels,
>             'pixel_values': pixel_values,
>             'image_sizes': image_sizes,
>         }
>         return inputs



when I integrated this code, it gives me this error 
labels = torch._C._nn.pad_sequence(
RuntimeError: The size of tensor a (1966) must match the size of tensor b (1952) at non-singleton dimension 2

if I set the batch size greater than 1 per gpu

**Comment by mohbattharani** [comment]
I had the same error, so I tried the following: 

`input_ids = torch.nn.utils.rnn.pad_sequence(all_input_ids, batch_first=True, padding_value=self.processor.tokenizer.pad_token_id)
        print (input_ids.shape)
        labels = torch.nn.utils.rnn.pad_sequence(all_label_ids, batch_first=True, padding_value=IGNORE_INDEX).unsqueeze(1)
        print (labels.shape)
        `
With `batch_size =2`, I have following shapes input_ids and labels:

Each sample:
```
torch.Size([3055, 1]) torch.Size([3055, 1])
torch.Size([2820, 1]) torch.Size([2820, 1])
```

Batch:
```
torch.Size([2, 3055, 1])
torch.Size([2, 1, 3055, 1])
```

I still have memory overflow issue, trying to solve it.
