### ISSUE TITLE
How to have an inference with fine tuned Phi-3-V

### ISSUE THREAD

**Issue by WYY220062** [microsoft/Phi-3CookBook#91]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> I would like to learn how to set up an inference with the model under /04.Finetuning/vision_finetuning/output.
And Is the Phi-3-V fine tuning can support custom data?

### OS and Version?

> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by leestott** [comment]
Hi see https://huggingface.co/blog/mjbuehler/phi-3-vision-cephalo-moe its a nice walkthrough
