### ISSUE TITLE
QLoRA parameters missing in 04.Finetuning /Phi-3-finetune-qlora-python.ipynb

### ISSUE THREAD

**Issue by p-prakash** [microsoft/Phi-3CookBook#94]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a:
```
- [x ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> While trying to execute the notebook [Phi-3-finetune-qlora-python.ipynb](https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/Phi-3-finetune-qlora-python.ipynb), initializing the class `SFTTrainer` fails because the QLoRA parameters are not defined hence the variables `peft_config` and `args` are undefined. Looks like it's a copy paste mistake where **Load the tokenizer and model to finetune** code cell was duplicated instead of having the code cell for QLoRA parameters.

### Any log messages given by the failure
> 

### Expected/desired behavior
> QLoRA parameters should be defined hence the SFTTrainer class should be initialized without any issue.

### OS and Version?
> Ubuntu 20.04.6 LTS on Azure ML Compute Instance software version Linux 24.06.10

### azd version?
> azd is not installed. Is it a requirement?

> ---------------------------------------------------------------

**Comment by leestott** [comment]
@skytin1004 thanks for resolving this issue. Excellent PR proposal

**Comment by leestott** [comment]
@
