### ISSUE TITLE
Please use the new Azure AI Inference SDK for MaaS/MaaP inference

### ISSUE THREAD

**Issue by dargilco** [microsoft/Phi-3CookBook#96]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Feature request

Microsoft now has its own SDK for AI Model inference, for different models hosted on MaaS/MaaP. Python and JS versions are out. C# will be released next.  For Python, see https://learn.microsoft.com/en-us/python/api/overview/azure/ai-inference-readme?view=azure-python-preview. The SDK uses the REST API documented here: https://learn.microsoft.com/en-us/azure/ai-studio/reference/reference-model-inference-api?tabs=python . 

Please add section in your cookbook on using this SDK for phi3 models hosted on MaaS/MaaP. Thanks!

**Comment by leestott** [comment]
@dargilco please feel free to make a PR for MaaS and MaaP and include some E2E samples.

**Comment by leestott** [comment]
@dargilco added https://github.com/microsoft/Phi-3CookBook/blob/main/md/02.QuickStart/AzureModel_Inference.md please let me know if this resolves the issue
